// vue/src/Question.vue
<template>
    <div>
        <h2>{{ statement }}</h2>
        <button v-for="opt in options" :key="opt" @click="selected(opt)">{{ opt }}</button>
    </div>
</template>

<script>
export default {
    name: 'Question',
    props: ['statement', 'options'],
    methods: {
        selected: function(option) {
            console.log('você clicou em ', option);
            this.$emit('selection', option)
        }
    }
}
</script>

<style>

</style>

// react/src/Question.js
import React, { useState } from 'react'
import './question.css'

function Question(props) {
    const [selection, setSeletion] = useState('')
    
    function click(opt) {
        props.onSelect(opt)
        setSeletion(opt)
    }

    const options = props.options.map(opt => {
        return <button
            key={opt}
            className = { selection === opt ? 'selected' : null }
            onClick= { () => click(opt) }
        >{ opt }</button>
    })
    return <div>
        <h2>{ props.statement }</h2>
        { options }
    </div>
}

export default Question;
