// vue/src/Quiz.vue
<template>
  <div>
      <Question
        :statement="questions[currentQuestion].statement"
        :options="questions[currentQuestion].options"
        @selection="onSelection($event)"
        ></Question>
      <button @click="next">Próximo</button>
      <Results v-if="showResults" :answers="answers"></Results>
  </div>
</template>

<script>
import Vue from 'vue'
import Question from './Question.vue'
import Results from './Results.vue'

export default {
    name: 'Quiz',
    components: {
        Question,
        Results
    },
    data: () => {
        return {
            questions: [
                {
                    statement: 'Esta é a 1ª questão',
                    options: ['aaa', 'bbb', 'ccc']
                },
                {
                    statement: 'Esta é a 2ª questão',
                    options: ['aaa', 'bbb', 'ccc', 'ddd']
                },
            ],
            currentQuestion: 0,
            showResults: true,
            answers: []
        }
    },
    methods: {
        next: function() {
            if (this.currentQuestion < this.questions.length - 1) {
                this.currentQuestion++
            }
            else {
                this.showResults = true
            }
        },
        onSelection: function(option) {
            // this.answers[this.currentQuestion] = option
            Vue.set(this.answers, this.currentQuestion, option)
        }
    }
}
</script>

<style>

</style>

// react/src/Quiz.js
import React from 'react';
import Results from './Results';
import Question from './Question';

class Quiz extends React.Component {
    questions = [
        {
            statement: 'Qual a cor do cavalo branco de Napoleão?',
            options: ['preto', 'branco', 'azul', 'verde']
        },
        {
            statement: 'Qual a cor do cavalo azul de Napoleão?',
            options: ['preto', 'branco', 'azul', 'verde']
        },
    ]

    constructor(props) {
        super(props)
        this.state = {
            showResults: false,
            currentQuestion: 0,
            answers: []
        }
    }

    next() {
        if (this.state.currentQuestion < this.questions.length - 1) {
            this.setState({
                currentQuestion: this.state.currentQuestion + 1
            })
        }
        else {
            this.setState({
                showResults: true
            })
        }
    }

    selected(answer) {
        this.state.answers.push(answer)
        this.setState({
            answers: this.state.answers
        })
    }

    render() {
        const results = this.state.showResults? <Results answers={ this.state.answers }></Results> : null;

        return (
            <div>
                <Question
                    statement={ this.questions[this.state.currentQuestion].statement }
                    options={ this.questions[this.state.currentQuestion].options }
                    onSelect={ opt => this.selected(opt) }
                ></Question>
                <button onClick={ () => this.next() }>Próximo</button>
                { results }
            </div>
        );
    }
}

export default Quiz;
