// quiz-react/src/Question.js
import React from 'react'

export default class Question extends React.Component {
  render() {
    const options = this.props.options.map((option, index) => (
      <button
        key={option}
        className={index === this.props.selection ? 'm5 selected' : 'm5'}
        onClick={() => this.props.onSelect(index)}
      >
        {option}
      </button>
    ))

    return (
      <div>
        <h1>{this.props.statement}</h1>
        {options}
      </div>
    )
  }
}

// vue/src/Question.vue
<template>
    <div>
        <h2>{{ statement }}</h2>
        <button v-for="opt in options" :key="opt" @click="selected(opt)">{{ opt }}</button>
    </div>
</template>

<script>
export default {
    name: 'Question',
    props: ['statement', 'options'],
    methods: {
        selected: function(option) {
            console.log('você clicou em ', option);
            this.$emit('selection', option)
        }
    }
}
</script>

<style>

</style>
